server {
    listen 80;
    server_name admin.getpickupdrop.com;

    root /var/www/pickupdrop-admin;
    index index.html;

    location / {
        try_files $uri /index.html;   # SPA fallback
    }
}
