spring:
  application:
    name: pickupdrop-backend
  profiles:
    default: loc
    group:
      loc: 'common,loc,actuator,flyway'
      dev: 'common,dev,actuator,flyway'
      pro: 'common,pro,actuator,flyway'
